# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "simple"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				panda = true
				bee = true
				axolotl = true
				arrow = true
				cow = true
				pig = true
				allay = true
				skeleton = true
				llama = true
				bat = true
				husk = true
				hoglin = true
				camel = true
				rabbit = true
				silverfish = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				turtle = true
				salmon = true
				wandering_trader = true
				piglin_brute = true
				ocelot = true
				horse = true
				phantom = true
				ender_dragon = true
				glow_squid = true
				warden = true
				glow_item_frame = false
				squid = true
				tnt = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				chicken = true
				trader_llama = true
				donkey = true
				evoker_fangs = true
				chest_minecart = true
				fox = true
				tropical_fish = true
				slime = true
				pillager = true
				iron_golem = true
				area_effect_cloud = true
				zombified_piglin = true
				blaze = true
				piglin = true
				cat = true
				zombie = true
				guardian = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				wolf = true
				skeleton_horse = true
				zombie_villager = true
				block_display = true
				elder_guardian = true
				boat = true
				strider = true
				polar_bear = true
				painting = true
				cave_spider = true
				witch = true
				cod = true
				spider = true

			[light_sources.settings.entities.promenade]
				sunken_skeleton = true
				capybara = true
				duck = true

			[light_sources.settings.entities.unicopia]
				thrown_item = true
				butterfly = true
				air_balloon = true
				floating_artefact = true

			[light_sources.settings.entities.terraform]
				boat = true

